version: "3"
networks:
  docker-mysql_default:
    external: true 
services:
  pts-backend:
    networks:
      - docker-mysql_default
    environment:
      - FLASK_APP=/usr/src/app/app.py
    build: .
    ports:
      - "2000:5001"
    container_name: flaskapp
    volumes:
      - ./app:/usr/src/app
    command: flask run --host=0.0.0.0 --port=5001